steps:
  - label: "WeakConvergence"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      queue: "juliacpu"
    env:
      GROUP: 'WeakConvergence'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "WeakAdaptive"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.5"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'WeakAdaptive'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
